### ISSUE TITLE
`eslint-plugin-typescript` was renamed to `@typescript-eslint/eslint-plugin`

### ISSUE THREAD

**Issue by sindresorhus** [stefanbuck/eslint-rule-docs#4]
And docs now live at https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/eslint-plugin/docs/rules

**Comment by sindresorhus** [comment]
Off topic, but the repo URL in your package.json is incorrect.

**Comment by stefanbuck** [comment]
Sorry for the delay on this, but somehow I missed the notification for this issue. This repo needs some updates since the travis cronjob stopped working. Will fix it this weekend and update the name + url of `eslint-plugin-typescript`

**Comment by stefanbuck** [comment]
They switch to a mono repo too, so I had to adjust the script to take that into account as well. Should be all good now.
